export const OPERATIONAL_ERROR_CODES = [
  "AUTH_BOOTSTRAP_FAILED",
  "EXAM_SESSION_CREATE_FAILED",
  "EXAM_REQUIRED_AUDIO_FAILED",
  "EXAM_PRELUDE_FAILED",
  "ANSWER_RECORDING_FAILED",
  "ANSWER_SUBMISSION_FAILED",
  "EXAM_GRADING_FAILED",
  "FEEDBACK_PAGE_LOAD_FAILED",
  "FEEDBACK_DATA_LOAD_FAILED",
  "FEEDBACK_HISTORY_LOAD_FAILED",
  "SUMMARY_FEEDBACK_RETRY_FAILED",
  "REANSWER_QUESTION_LOAD_FAILED",
  "REANSWER_SUBMISSION_FAILED",
  "REANSWER_GRADING_FAILED",
  "LEARNING_RECORD_DELETE_FAILED",
  "QUALITY_REVIEW_CONSENT_UPDATE_FAILED",
  "API_RESPONSE_VALIDATION_FAILED",
] as const;

export type OperationalErrorCode = (typeof OPERATIONAL_ERROR_CODES)[number];

const OPERATIONAL_ERROR_CODE_SET: ReadonlySet<string> = new Set(
  OPERATIONAL_ERROR_CODES,
);

export function isOperationalErrorCode(value: unknown): value is OperationalErrorCode {
  return typeof value === "string" && OPERATIONAL_ERROR_CODE_SET.has(value);
}
